### ISSUE TITLE
Use a signatur in combination with a hash

### ISSUE THREAD

**Issue by wagnerchris** [nikeee/license-system#1]
Hi, this is more an idea than a problem.
The problem of a Signatur is the size of the license file. The size of the file is doubled.
Generate a hash like one of the SHA-2 family of your licenseparameters. Then sign the hash. In your verify application with the public key, you have to generate a new hash of your license paramter and compare the new hash with your hash in the signatur. 
An advantage of using a hash is when someone manipulate a letter in your license parameters, the hash is quite different than before and the size of a hash is always the same like 256 or 512 bit.

Best regards Chris.

**Comment by nikeee** [comment]
We are already using a hash (sha-1) in this case. We could update the code to use a newer hash function.

**Comment by wagnerchris** [comment]
Sorry. Yes you are right. I've overlooked.
