### ISSUE TITLE
Sicherheitsbedenken

### ISSUE THREAD

**Issue by Gordrin** [nikeee/license-system#2]
Hallo,

ich hab mir das mal angeschaut und denke dass es ein Sicherheitsproblem gibt. Bzw. ich mir einfach selber Lizenzen erstellen kann.

Dafür muss ich einfach meinen eigenen privaten Key nutzen, eine gültige Lizenz Signieren (SHA-1) und deinen PublicKey.xml File durch meinen public Key ersetzen. 
Sofern ich die Lizenz inhaltlich identisch erstelle wie dein Programm es erwartet, sollte dein Programm nun die Lizenz laden, mit dem public Key (meinem Key) die Lizenz auf gültigkeit überprüfen und feststellen dass die Lizenz gültig ist (da ich diese ja mit meinem Key-Value-Paar) erstellt habe.

Mich würden deine Gedanken dazu intessieren, ob ich etwas übersehe.

Gruß Stefan

**Comment by nikeee** [comment]
Natürlich geht das, der "Angriff" existiert immer.

Der Public-Key hat man allerdings üblicherweise Hartkodiert in der Anwendung. Auch da kann man ihn austauschen/umpatchen, klar. Dafür muss man das aber für jede neue Version extra machen. Wenn man will, kann man die Assembly dann noch mittels Code-Signing signieren.

Wie weiter unten beschrieben: Den Perfekten Schutz gibt's nicht. Dieser hat den Vorteil, dass man keine Lizenzen uneingeschränkt ausstellen kann, ohne zu patchen.

Oder was genau meinst du?

**Comment by Gordrin** [comment]
Ja ich stimme dir vollkommen zu, den perfekten Schutz gibt es tatsächlich nicht. 

Der Blog hat sich nur so gelesen als ob der Public Key als Datei im Filesystem bereitgestellt wird und daraufhin hab ich ein wenig über Angriffsmechanismen nachgedacht (da ich momentan an einer Lizenzierungslösung für eine Anwendung arbeite bei der ich nahe an deinem Konzept bin). 

Du hast auch recht damit dass man den Public Key in der dll hat und dieser ggf. ausgetauscht werden könnte. Ebenso kann man die dll austauschen (geht scheinbar auch mit signierten dll's).

Aber wie du auch schon geschrieben hast geht es ja nur darum einen gewissen Schutz einzurichten.

Danke dir für deine schnelle Antwort.

**Comment by nikeee** [comment]
Man kann auch die Assembly patchen, die die RSA-Klasse enthält und die entsprechenden Verify-Methoden abändern. Dann hätte man das Ganze systemweit ausgehebelt.
